export interface Person {
    "id": number,
    "title": string,
    "gender": number,
    "first_name": string,
    "middle_name": string | null,
    "last_name": string,
    "dob": string,
    "hebrew_first_name": string | null,
    "hebrew_middle_name": string | null,
    "hebrew_last_name": string | null,
    "contact_phone": string | null,
    "contact_phone_normalized": string | null,
    "contact_email": string | null,
    "corporate_phone": string | null,
    "corporate_phone_normalized": string | null,
    "corporate_email": string | null,
    "state": string | null,
    "country": string | null,
    "city": string | null,
    "address": string | null,
    "zip": string | null,
    "phone": string | null,
    "created_at": string | null,
    "updated_at": string | null
}
