stages:
  - build
  - deploy

variables:
  DEVELOPMENT_SERVER_USERNAME: devops
  DEVELOPMENT_SERVER_IP: 35.211.160.56

storybook_build:
  only:
    - storybook
  stage: build
  image: trion/ng-cli
  script:
    - rm -rf ./node_modules/
    - df . -h
    - npm i --only=prod
    - df . -h
    - npm run build-storybook
    - ls -la
  artifacts:
    expire_in: 10 min
    paths:
      - ./dist/storybook/

storybook_deploy:
  only:
    - storybook
  image: alpine
  stage: deploy
  before_script:
    - apk add --no-cache openssh
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" >> ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
  script:
    - apk add --no-cache rsync
    - rsync -rav --delete --rsync-path="sudo rsync" storybook/ $DEVELOPMENT_SERVER_USERNAME@$DEVELOPMENT_SERVER_IP:/var/www/app-fe/storybook/
