stages:
  - build
  - deploy

variables:
  DEVELOPMENT_SERVER_USERNAME: devops
  DEVELOPMENT_SERVER_IP: 35.211.160.56

image: trion/ng-cli

before_script:
  - apk add --no-cache openssh
  - mkdir -p ~/.ssh
  - echo "$SSH_PRIVATE_KEY" >> ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config


storybook_build_and_deploy:
  only:
    - storybook
  stage: build
  before_script: []
  script:
    - npm i --only=prod
    - npm run build-storybook
    - apk add --no-cache rsync
    - rsync -rav --delete --rsync-path="sudo rsync" storybook/ $DEVELOPMENT_SERVER_USERNAME@$DEVELOPMENT_SERVER_IP:/var/www/app-fe/storybook/
  artifacts:
    expire_in: 1 day
    paths:
      - storybook/