stages:
  - merge
  - build
  - deploy

variables:
  DEVELOPMENT_SERVER_USERNAME: devops
  DEVELOPMENT_SERVER_IP: 35.211.160.56

image: alpine

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - node_modules/

before_script:
  - apk add --no-cache openssh
  - mkdir -p ~/.ssh
  - echo "$SSH_PRIVATE_KEY" >> ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config


merge_build:
  only:
    - merge_request
  stage: merge
  image: trion/ng-cli
  before_script: []
  script:
    - npm i
    - npm run build
  artifacts:
    expire_in: 1 day
    paths:
      - dist/

development_build:
  only:
    - development
  stage: build
  image: trion/ng-cli
  before_script: []
  script:
    - npm i
    - npm run build
  artifacts:
    expire_in: 1 day
    paths:
      - dist/

storybook_build:
  only:
    - storybook
  stage: build
  image: trion/ng-cli
  before_script: []
  script:
    - npm i
    - npm run build-storybook
  artifacts:
    expire_in: 1 day
    paths:
      - storybook/

storybook_deploy:
  only:
    - storybook
  stage: deploy
  script:
    - apk add --no-cache rsync
    - rsync -rav --delete --rsync-path="sudo rsync" storybook/ $DEVELOPMENT_SERVER_USERNAME@$DEVELOPMENT_SERVER_IP:/var/www/app-fe/storybook/

    