export enum ButtonColorsEnum {
  GRAY = 'gray',
  GREEN = 'green',
  PURPLE = 'purple',
  TRANSPARENT = 'transparent',
  TRANSPARENT_GRAY = 'transparent-gray',
  YELLOW = 'yellow',
  WHITE = 'white',
  LIGHT_BLUE = 'light-blue',
  GRAY_PURPLE = 'gray-purple',
  DARK_BLUE = 'status-dark-blue',
  BLUE = 'status-blue',
  RED = 'status-red',
  LIGHT_PURPLE = 'status-light-purple',
  ORANGE = 'orange-button',
}
