export interface StudentInfo {
  student_current_grade: string,
  student_start_grade: string,
  student_current_school: string,
  student_previous_school: string,
  student_medical_conditions: string,
  student_allergies: string,
  student_medications: string,
  student_physician: string,
  student_physician_country: string,
  student_physician_address: string,
  student_physician_phone: string,
  student_first_contact_relationship: string,
  student_first_contact_full_name: string,
  student_first_contact_cell_phone: string,
  student_second_contact_full_name: string,
  student_second_contact_relationship: string,
  student_second_contact_cell_phone: string,
}