export enum IconsEnum {
  COPY = 'fa-copy',
  DOWNLOAD = 'fa-download',
  EYE = 'fa-eye',
  PEN = 'fa-pen',
  SHARE = 'fa-share-alt',
  CARET_DOWN = 'fa-caret-down',
  CARET_UP = 'fa-caret-up',
  SETTINGS = 'fa-cog',
  CROSS = 'fa-times',
  TRASH = 'fa-trash',
  ZOOM_IN = 'fa-search-plus',
  ZOOM_OUT = 'fa-search-minus',
  CARET_RIGHT = 'fa-caret-right',
  CARET_LEFT = 'fa-caret-left',
}
